### ISSUE TITLE
userProvider.get() hard to do over in my example

### ISSUE THREAD

**Issue by andrewarrow** [psamsotha/jersey-okhttp-interceptor-demo#2]
https://github.com/psamsotha/jersey-okhttp-interceptor-demo/blob/b3b2da00b284e75011ea780fb37b555ea581ac96/src/main/java/com/example/stackoverflow/client/ClientBinder.java#L89

I looks like you are calling userProvider.get() inside intercept and that will call:

https://github.com/psamsotha/jersey-okhttp-interceptor-demo/blob/b3b2da00b284e75011ea780fb37b555ea581ac96/src/main/java/com/example/stackoverflow/client/UserFactory.java#L19

which will make a new User object which has a null name or not. And then isValid() does it's trick and this is the key to the whole system.

And you pass in:

https://github.com/psamsotha/jersey-okhttp-interceptor-demo/blob/b3b2da00b284e75011ea780fb37b555ea581ac96/src/main/java/com/example/stackoverflow/client/ClientBinder.java#L56

`Provider<User> userProvider` at the time you create the OkHttpClient. But over in my example:

https://github.com/andrewarrow/web-wash/blob/19e58d49abbe54d5f88c4358de5a604acd1dd3fb/src/team/higher/web/runtime/module/ClientModule.kt#L48

I have this:

  `@Provides`
  `@Singleton`
  `fun provideX(): X {`
    `return X`
  `}`

system for making "providers". I'm lost as to how to do the dynamic creation of the User object with `userProvider.get()` equivalent using the framework I already have in place with these provideX methods.

**Comment by psamsotha** [comment]
I've never really used Dagger for DI so it's not something I could answer off the top of my head. The example I made just used the DI system already built into Jersey. Is there a specific reason for using Dagger? It looks like to me that there is more work (e.g. needing to provide the resources and filters, etc as part of the DI system) involved trying to use Dagger as opposed to using the built it DI.

**Comment by andrewarrow** [comment]
here are comments I got, sorry for this game of telephone, I appreciate all the attention you give this: 

> you can't mix Dagger with tradition DI
because they use reflection
Even if it compiles, it still can crash
with Dagger, you will never have that issue

> So it works if we provide all clients through jersey Factory
> but that would make our compiler time DI become runtime DI
> The problem is
> `RequestScope.class`
> So in other to get a DI object using `@Inject`
> it must be in inside our `AbcResource` class
> CookieInterceptor is inside Retrofit
> 
> Not sure if I can find a hack to somehow get this object out
> try to `@Inject` client inside our `Resource` class
> everything like Factory thing are just noise
> He has no factory for `ContainerRequest`
> which means this class magically got injected by runtime Jersey
> 
> Notice the `RequestScoped.class`
> that's required for `ContainerRequest`
> we just need to set that container request object
> for CookieInterceptor

**Comment by psamsotha** [comment]
Might be possible using the approach in [this comment](https://github.com/google/dagger/issues/427#issuecomment-238074691) (adding Guice as a middleman). Something I would have to play with. But I think the end result would still be partly a "runtime" DI.
